### DISCUSSION TITLE
oddo on startup

### DISCUSSION THREAD

**Discussion by mhamidjamil** [mhamidjamil/orangePi#52] [General]
Here is how I run Odoo script on startup:

- Create a `docker-compose.yml` and write this content in it:

```
version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    restart: always

  odoo:
    image: odoo:latest
    ports:
      - "8069:8069"
    links:
      - db:db
    restart: always
```

- To start the containers:
`docker-compose up -d`

- To stop and remove the containers:
`docker-compose down`

- Create service file:
`sudo nano /etc/systemd/system/docker-compose-odoo.service`

- Write this content in it:
```
[Unit]
Description=Docker Compose for Odoo
After=docker.service
Requires=docker.service

[Service]
Restart=always
WorkingDirectory=/path/to/your/docker-compose-directory
ExecStart=/usr/local/bin/docker-compose up -d
ExecStop=/usr/local/bin/docker-compose down

[Install]
WantedBy=default.target
```

- After creating the service file, reload the systemd configuration:
` sudo systemctl daemon-reload`
- Enable the service to start on boot:
`sudo systemctl enable docker-compose-odoo.service`
