### DISCUSSION TITLE
Setup a HomeLab manager

### DISCUSSION THREAD

**Discussion by mhamidjamil** [mhamidjamil/orangePi#75] [Ideas]
I installed Dashy to manage all my Orange Pi hosted sites.

**Comment by mhamidjamil** [comment]
1. I created a folder `docker/dashy` and then created a conf.yml file and past this content in it: 
you can also copy past from [here](https://dashy.to/docs/quick-start)
```
pageInfo:
  title: Home Lab
sections: # An array of sections
- name: Example Section
  icon: far fa-rocket
  items:
  - title: GitHub
    description: Dashy source code and docs
    icon: fab fa-github
    url: https://github.com/Lissy93/dashy
  - title: Issues
    description: View open issues, or raise a new one
    icon: fas fa-bug
    url: https://github.com/Lissy93/dashy/issues
- name: Local Services
  items:
  - title: Firewall
    icon: favicon
    url: http://192.168.1.1/
  - title: Game Server
    icon: https://i.ibb.co/710B3Yc/space-invader-x256.png
    url: http://192.168.130.1/

```
I [clone](https://github.com/walkxcode/dashboard-icons) this repo in same folder (for icons).
I create a stack in portainer names it dashy-yt and past this in **web editor**:
```
  version: '3.3'
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    ports:
      - '8880:80'
    volumes:
      - /home/orangepi/docker/dashy/conf.yml:/app/public/conf.yml
      - /home/orangepi/docker/dashy/dashboard-icons/png:/app/public/item-icons/icons
    restart: unless-stopped
```
Then deploy the stack.
